

const images ={
    actor1 : require('../assets/image/actor1.png'),
    actor2 : require('../assets/image/actor2.png'),
    actor3 : require('../assets/image/actor3.png'),
    rightArrow: require('../assets/image/rightArrow.png'),
    bell: require('../assets/image/bell.png'),
    calendarW: require('../assets/image/calendar.png'),
    calendarG: require('../assets/image/calendarB.png'),
    paymentMethod1: require('../assets/image/card1.png'),
    paymentMethod2: require('../assets/image/card2.png'),
    paymentMethod3: require('../assets/image/card3.png'),
    paymentMethod4: require('../assets/image/card4.png'),
    paymentMethod5: require('../assets/image/card5.png'),
    cart: require('../assets/image/cart.png'),
    chair: require('../assets/image/chairB.png'),
    clockW: require('../assets/image/clock.png'),
    clockB: require('../assets/image/clockB.png'),
    director1 : require('../assets/image/director1.png'),
    director2 : require('../assets/image/director2.png'),
    discount: require('../assets/image/discount.png'),
    ellipseL: require('../assets/image/ellipseL.png'),
    ellipseR: require('../assets/image/ellipseR.png'),
    error: require('../assets/image/error.png'),
    facebook: require('../assets/image/facebook.png'),
    faceId: require('../assets/image/faceid.png'),
    barcode: require('../assets/image/frame.png'),
    locationImage: require('../assets/image/locationImage.png'),
    google: require('../assets/image/google.png'),
    image1 : require('../assets/image/image1.png'),
    image2 : require('../assets/image/image2.png'),
    movieimage1 : require('../assets/image/movieimage1.png'),
    movieimage2 : require('../assets/image/movieimage2.png'),
    movieimage3 : require('../assets/image/movieimage3.png'),
    movieimage4 : require('../assets/image/movieimage4.png'),
    movieimage5 : require('../assets/image/movieimage5.png'),
    movieimage6 : require('../assets/image/movieimage6.png'),
    movieimage7 : require('../assets/image/movieimage7.png'),
    language : require('../assets/image/language.png'),
    leftArrow : require('../assets/image/leftArrow.png'),
    locationW: require('../assets/image/location.png'),
    locationB : require('../assets/image/locationB.png'),
    lock : require('../assets/image/lock.png'),
    logo : require('../assets/image/logo.jpeg'),
    logo2 : require('../assets/image/logo2.jpeg'),
    moneySend : require('../assets/image/moneysend.png'),
    news1 : require('../assets/image/news1.png'),
    news2 : require('../assets/image/news2.png'),
    note : require('../assets/image/noteB.png'),
    phone : require('../assets/image/phone.png'),
    profile : require('../assets/image/profile.png'),
    promo : require('../assets/image/promo.png'),
    search : require('../assets/image/search.png'),
    seeall : require('../assets/image/seeall.png'),
    service1 : require('../assets/image/service1.png'),
    service2 : require('../assets/image/service2.png'),
    service3 : require('../assets/image/service3.png'),
    service4 : require('../assets/image/service4.png'),
    tab1 : require('../assets/image/tab1.png'),
    tab2 : require('../assets/image/tab2.png'),
    tab3 : require('../assets/image/tab3.png'),
    tab4 : require('../assets/image/tab4.png'),
    ticket : require('../assets/image/ticket.png'),
    video : require('../assets/image/video.png'),
    videoB : require('../assets/image/videoB.png'),
    videoPlay : require('../assets/image/videoplay.png'),
    exit: require('../assets/image/exit.png'),
    terms: require('../assets/image/terms.png'),
    help: require('../assets/image/question.png'),
    support: require('../assets/image/support.png'),
    setting: require('../assets/image/setting.png'),
}

export default images