import {StyleSheet} from 'react-native';
import color from '../../config/colors';

const style = StyleSheet.create({
  areaview: {
    flex: 1,
    backgroundColor: color.black,
  },
  rendermainview: {flex: 1, marginHorizontal: 16},
  pressableinnerview: {
    marginVertical: 10,
    gap: 10,
    marginHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  pressabletext: {
    color: color.white,
    fontWeight: 'bold',
    fontSize: 16,
    alignItems: 'center',
  },
  pressableimage:{alignItems: 'center'},
  titlestyle: {
    flex: 1,
    color: color.white,
    fontSize: 28,
    textAlign: 'left',
    fontWeight: '600',
    justifyContent: 'flex-start',
  },
  card: {
    flexDirection: 'row',
    backgroundColor: color.cocoBlack,
    borderRadius: 12,
    marginBottom: 16,
    alignItems: 'center',
  },
  poster: {
    width: 99,
    height: 137,
    borderRadius: 10,
  },
  seatdetailview:{justifyContent: 'space-between', flexDirection: 'row'},
  seatdetailmainview:{gap: 20, marginBottom: 24},
  cardContent: {
    marginLeft: 16,
    flex: 1,
  },
  card2subview:{flexDirection: 'row', alignItems: 'center', flex: 1},
  textinput:{fontSize: 14, color: color.white, flex: 1},
  touchabletext:{color: color.black, fontSize: 16},
  title: {
    color: color.white,
    fontSize: 20,
    fontWeight: 'bold',
  },
  discounticon:{width: 20, height: 20, marginHorizontal: 10},
  meta: {
    color: color.darkGray,
    marginTop: 6,
  },
  genreIcon: {
    width: 16,
    height: 16,
    marginRight: 6,
    marginTop: 5,
  },
  iconview: {flexDirection: 'row', alignItems: 'center'},
  subtext: {
    color: color.white,
    fontSize: 16,
  },
  button: {
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: color.vibrantHoney,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    width: 119,
  },
  card2: {
    flexDirection: 'row',
    backgroundColor: color.cocoBlack,
    borderRadius: 8,
    height: 40,
    justifyContent: 'space-between',
  },
  divider: {
    height: 1,
    backgroundColor: color.knightsArmor,
    marginTop: 32,
  },
  title2: {
    fontSize: 24,
    fontWeight: 'bold',
    color: color.white,
    marginTop: 20,
  },
  selectedCard: {
    backgroundColor: color.mediumRoast,
    borderWidth: 1,
    borderColor: color.gold,
  },
  button2: {
    height: 56,
    borderWidth: 1,
    borderRadius: 64,
    backgroundColor: color.vibrantHoney,
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    flexDirection: 'row',
    backgroundColor: color.soulless,
    paddingHorizontal: 16,
    borderRadius: 12,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 32,
    height: 52,
  },
  text: {
    color: color.white,
    fontSize: 16,
    fontWeight: '500',
  },
  timer: {
    color: color.gold,
    fontSize: 16,
    fontWeight: 'bold',
  },
   contentContainerStyle:{marginTop: 16},
  touchablefont:{color: color.black, fontSize: 20},
});
export default style;
