import React from 'react';
import {StyleSheet} from 'react-native';
import color from '../../config/colors';

export const style = StyleSheet.create({
  // textstyle:{
  // color:'#fff',
  // fontSize:28,
  // textAlign:'center',
  // flexDirection:'row',
  // },
  safearea: {flex: 1, backgroundColor: color.black},
  scrollViewContainerStyle: {
    flexGrow: 1,
    paddingHorizontal: 16,
    justifyContent: 'space-between',
    paddingTop: 48,
    paddingBottom: 32,
  },
  scrollsubview:{marginBottom: 32},
  textinputview:{flexDirection: 'row', alignItems: 'center', gap: 16},
  textinput:{fontSize: 24, color: color.white},
  phone: {
    height: 32,
    width: 32,
    flexDirection: 'row',
  },
  divider: {
    height: 1,
    backgroundColor: color.white,
    marginHorizontal: 16,
    marginTop: 12,
  },
  button: {
    height: 56,
    borderWidth: 1,
    // borderColor: 'red',
    borderRadius: 64,
    backgroundColor: color.vibrantHoney,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttontext:{color: color.black, fontSize: 20},
  button1: {
    height: 56,
    borderWidth: 1,
    borderColor: color.cocoBlack,
    borderRadius: 64,
    backgroundColor: color.cocoBlack,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6.5,
  },
  socialmediabuttontext:{color: color.white, fontSize: 16, fontWeight: 'bold'},
  socialmediaview:{gap: 16, marginTop: 16},
  button2: {
    height: 56,
    borderWidth: 1,
    borderColor: color.cocoBlack,
    borderRadius: 64,
    backgroundColor: color.cocoBlack,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4.74,
  },
  termstyle: {
    color: color.tangledWeb,
    textAlign: 'center',
    marginTop: 40,
    fontSize: 12,
    marginBottom: 31,
  },
  orText: {
    textAlign: 'center',
    color: color.errigalWhite,
    marginBottom: 40,
  },
  facebookimg:{height: 24, width: 12.39},
  googleimg:{height: 20, width: 20},
  err: {
    color: color.red,
    fontSize: 14,
    marginBottom: 5,
    marginTop: 10,
    marginHorizontal: 16,
  },
});
